- name: restart win sshd
  win_service:
    name: sshd
    state: restarted

- name: restart win rdp
  win_service:
    name: TermService
    state: restarted
    force_dependent_services: yes
